FROM public.ecr.aws/docker/library/python:3.12-slim

ENV PORT=8090
WORKDIR /var/task
COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

COPY *.py ./
CMD exec uvicorn --port=$PORT index:app