FROM public.ecr.aws/docker/library/python:3.12-slim

ENV PORT=8090
WORKDIR /var/task
COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

EXPOSE 8090

COPY *.py ./
CMD ["uvicorn", "index:app", "--host", "0.0.0.0", "--port", "8090"]